### ISSUE TITLE
Cannot open any emails after upgrading KDE PIM from 16.08 to 16.12

### ISSUE THREAD

**Issue by cardonator** [KrissN/akonadi-ews#23]
I referenced this problem in #20 and #22 but I figured it was discrete enough from the titles of those issues to open a new ticket.

Ever since upgrading to akonadi 16.12 and KMail 5.4.0 around two weeks ago, I can no longer open any of the emails I have in my list. The list of emails still loads just fine, and most of the time checking mail does eventually download the email list correctly.

However, whenever I click on an email, the message pane just says "Retrieving Folder Contents Please wait . . .". At the bottom of the KMail window I frequently get a message that says "Unable to fetch item from backend (collection -1): Unable to retrieve item from resource: Did not receive a reply. Possible..." and nothing else happens.

I also noticed that in the regular akonadi logs, if I open an email that it thinks I have already viewed it never seems to send any requests to the Exchange resource to collect the email text like it used to on previous versions of akonadi. I even turned on the verbose logging and I still don't get anything that appears to be useful on previously read emails (i.e. I get nothing other than the regular periodic checks that it does).

With the verbose logging on, if I click on an email that KMail thinks is new, I get this in the log every time:
```log_ews_resource_request: Starting GetEvents request (subId: FQBleDEuY29ycC5kaWdpY2VydC5jb20QAAAA7hRhMqAlUO7xbBiV58y0bJNFcyTNdQIEAAAAFr/j08Gc6dGhTMgyRV0eTM=, wmark: AQAAAGH6mPzTFJ9M7q1JdXMMZ2XRcEPAAAAAAE=)
log_ews_resource_proto: "<?xml version=\"1.0\"?><soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:m=\"http://schemas.microsoft.com/exchange/services/2006/messages\" xmlns:t=\"http://schemas.microsoft.com/exchange/services/2006/types\"><soap:Header><t:RequestServerVersion Version=\"Exchange2007_SP1\"/></soap:Header><soap:Body><m:GetEvents><m:SubscriptionId>FQBleDEuY29ycC5kaWdpY2VydC5jb20QAAAA7hRhMqARlUO7xbBiV58y0bJNFcyTNdQIEAAAAFr/j08Gc6dGhTMgyRV0eTM=</m:SubscriptionId><m:Watermark>AQAAAGH6mPzTFJ9Mmq1JdXMMZ2XRcEPAAAAAAE=</m:Watermark></m:GetEvents></soap:Body></soap:Envelope>\n"
log_ews_resource_proto: data KIO::TransferJob(0x151aa70) "<?xml version=\"1.0\" encoding=\"utf-8\"?><s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\"><s:Header><h:ServerVersionInfo MajorVersion=\"15\" MinorVersion=\"0\" MajorBuildNumber=\"1236\" MinorBuildNumber=\"1\" Version=\"V2_23\" xmlns:h=\"http://schemas.microsoft.com/exchange/services/2006/types\" xmlns=\"http://schemas.microsoft.com/exchange/services/2006/types\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"/></s:Header><s:Body xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\"><m:GetEventsResponse xmlns:m=\"http://schemas.microsoft.com/exchange/services/2006/messages\" xmlns:t=\"http://schemas.microsoft.com/exchange/services/2006/types\"><m:ResponseMessages><m:GetEventsResponseMessage ResponseClass=\"Success\"><m:ResponseCode>NoError</m:ResponseCode><m:Notification><t:SubscriptionId>FQBleDEuY29ycC5kaWdpY2VydC5jb20QAAAA7hRhMqARlUO7xbBiV58y0bJNFcyTNdQIEAAAAFr/j08Gc6dGhTMgyRV0eTM=</t:SubscriptionId><t:PreviousWatermark>AQAAAGH6mPzTFJ9Mm7q1JdXMMZ2XRcEPAAAAAAE=</t:PreviousWatermark><t:MoreEvents>false</t:MoreEvents><t:StatusEvent><t:Watermark>AQAAAGH6mPzTFJ9Mm7q1JdXMMZ0JRsEPAAAAAAE=</t:Watermark></t:StatusEvent></m:Notification></m:GetEventsResponseMessage></m:ResponseMessages></m:GetEventsResponse"
log_ews_resource_proto: data KIO::TransferJob(0x151aa70) "></s:Body></s:"
log_ews_resource_proto: data KIO::TransferJob(0x151aa70) "Envelope>"
log_ews_resource_proto: data KIO::TransferJob(0x151aa70) ""
log_ews_resource_proto: response dumped to "/tmp/akonadi-ews-XsHQ4ys/ews_xmldump_QF13791.xml"
log_ews_resource:  StatusEvent
log_ews_resource_request: Got GetEvents response (1 notifications, 1 events)
```

And the response dump:
```xml
<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Header><h:ServerVersionInfo MajorVersion="15" MinorVersion="0" MajorBuildNumber="1236" MinorBuildNumber="1" Version="V2_23" xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/></s:Header><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><m:GetEventsResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><m:ResponseMessages><m:GetEventsResponseMessage ResponseClass="Success"><m:ResponseCode>NoError</m:ResponseCode><m:Notification><t:SubscriptionId>FQBleDEuY29ycC5kadpY2ydC5jb20QAAA7hRhMqARlUO7xbBiV58y0bJNFcyTNdQIEAAAAFr/j08Gc6dGhTMgyRV0eTM=</t:SubscriptionId><t:PreviousWatermark>AQAAAGH6mzTFJ9Mm7q1JdXMMZ2RcEPAAAAAE=</t:PreviousWatermark><t:MoreEvents>false</t:MoreEvents><t:StatusEvent><t:Watermark>AQAAGH6mPzTFJ9Mmq1JdXMMZJRsEPAAAAAE=</t:Watermark></t:StatusEvent></m:Notification></m:GetEventsResponseMessage></m:ResponseMessages></m:GetEventsResponse></s:Body></s:Envelope>
```

(I modified a number of the strings in there in case you notice they don't match up any more or something, I can provide an unedited response via email if necessary)

Afterwards, nothing changes. The pane shows nothing and the same message appears at the bottom of the KMail window.

**Comment by KrissN** [comment]
What version of Akonadi EWS resource are you using? Have you built it from sources or installed a package?

I'm asking because there was a slight API change with Akonadi in KDE PIM 16.12, which is related to fetching of individual items.

**Comment by cardonator** [comment]
I am running the release of 0.8.1. It's kind of a pain for me to patch. I'm running KDE Neon User Edition (basically Ubuntu 16.04).

**Comment by AugisM** [comment]
Could You try to rebuild akonadi-ews after upgrade? It helps me when upgrading kmail in gentoo.

**Comment by cardonator** [comment]
It might help but I don't have a source build and I'm not really sure how to compile this project from source.

**Comment by KrissN** [comment]
I have reproduced this on one of my systems, which I have upgraded from 16.08 to 16.12 yesterday (without rebuilding akonadi-ews).

Once I have rebuilt akonadi-ews against KDE PIM 16.12 everything started working again.

I'll see if I can set-up a VM with KDE Neon and build a package for you.

**Comment by hlavki** [comment]
I had same behaviour in openSUSE Tumbleweed.

Dňa 7. 1. 2017 10:44 dopoludnia používateľ "Krzysztof Nowicki" <
notifications@github.com> napísal:

**Comment by cardonator** [comment]
@KrissN that would be awesome, thanks!

**Comment by barnsls** [comment]
Using Fedora 25. Installed akonadi-ews via akonadi-ews-0.8.1-1.fc24.x86_64.rpm from the download page. It has been working fine for the last month or so (I'm very impressed with it after years of using Evolution-ews) but today, after I let apper install a bunch of KDE patches, it exhibited the symptoms described above.  I did a 'dnf reinstall akonadi-ews-0.8.1-1.fc24.x86_64.rpm' and the problem went away. Figured that I should mention it in case it helps someone else.

**Comment by Kurisutian** [comment]
Hi! 
I'm also having the same problem on Manjaro after the latest update. However, I rebuild the package but it did not help. I still receive this error message.
Also rebuilding was a bit of a challenge since during the build process there is a file included which is not found there:
`In file included from /usr/include/KF5/AkonadiCore/exception.h:28:0,
                 from /usr/include/KF5/AkonadiCore/item.h:26,
                 from /usr/include/KF5/AkonadiCore/Item:1,
                 from /tmp/yaourt-tmp-cfoeller/aur-akonadi-ews-git/src/akonadi-ews/ewsfetchitemdetailjob.h:25,
                 from /tmp/yaourt-tmp-cfoeller/aur-akonadi-ews-git/src/akonadi-ews/calendar/ewsfetchcalendardetailjob.h:23,
                 from /tmp/yaourt-tmp-cfoeller/aur-akonadi-ews-git/src/akonadi-ews/calendar/ewscalendarhandler.cpp:24:
/usr/include/KF5/AkonadiCore/std_exception.h:1:44: schwerwiegender Fehler: /usr/include/c++/6.2.1/exception: Datei oder Verzeichnis nicht gefunden
 #include "/usr/include/c++/6.2.1/exception"
                                            ^
Kompilierung beendet.
make[2]: *** [CMakeFiles/akonadi_ews_resource.dir/build.make:106: CMakeFiles/akonadi_ews_resource.dir/calendar/ewscalendarhandler.cpp.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:101: CMakeFiles/akonadi_ews_resource.dir/all] Fehler 2
make: *** [Makefile:139: all] Fehler 2`
It says that /usr/include/c++/6.2.1/exception ist not found. I had to symlink /usr/include/c++/6.3.1/exception to it, since that's the correct version on my system. Still, after rebuilding, it did not solve the problem for me.

**Comment by cardonator** [comment]
Any update on getting a neon patch for this or maybe a 0.8.2 release with the fix?

**Comment by SasakiSadako** [comment]
It seems i have the same issue. but sometimes a restart of the akonadi server helps - not always.
im compiled the sources by myself for the newest kde Neon user Edition.
This is the output of my akonadiserver from the console this message is coming over and over again:
https://paste.ee/p/7I4T8

And here my Akonadi Console Debug output:
https://paste.ee/p/DT9Eb

Thank youtfor your great work, its to bad that it seems, you are the only person that work on Akonadi and Exchange. Maybe my logs will help.

**Comment by Fredba** [comment]
I have the same issue. 

Any news about rebuilding a deb package that works on KDE neon ?

**Comment by senarclens** [comment]
+1 :(

**Comment by Fredba** [comment]
I've rebuild a deb package from latest KDE Neon LTS and now it works :) 

@KrissN do you plan to continue developing the great work you have begun ?

**Comment by cardonator** [comment]
@Fredba care to share?

**Comment by Fredba** [comment]
Yes of course. You can download it from there : https://github.com/Fredba/repository

Let me know if it works for you

**Comment by cardonator** [comment]
Sweet! It works! How complicated is it to build on Neon? This is a case where I would have just built it myself but it seems rather complicated...

**Comment by Fredba** [comment]
It is not complicated, you've to install all dev libs needed before making a cmake. After I used checkinstall to create the deb package. I'm sorry I didn't saved my Virtual Machine so I cannot give you a step by step guide to rebuild this plugin.

**Comment by KrissN** [comment]
I have published the specification for Fedora and Ubuntu packages into a [separate repository](https://github.com/KrissN/akonadi-ews-packagespec). It is difficult for me right now to provide up-to-date builds for a wide range of distros. I'd be grateful for any help in this area.

@Fredba: I do intend to continue development - as you can see commits are coming in, only somewhat slowly due to time constraints.

**Comment by Kurisutian** [comment]
Unfortunately rebuilding the package on Manjaro Linux didn't solve the problem for me. Is there anything else you guys did to make it work again? Thanks!

**Comment by Fredba** [comment]
@KrissN this is very good news. Thank you again for the work you have already done
